import GlobalPopMsg from '@/components/GlobalPopMsg'
import TopMenuBtn from '@/components/TopMenuBtn'
import '@/styles/globals.scss'
import { Assistant } from 'next/font/google'

const font = Assistant({ subsets: ['latin'] })

export const metadata = {
  title: 'Roi Crm',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="he" dir="rtl">
      <body className={font.className}>
        <GlobalPopMsg />
        <section className="nav top-0">
          <TopMenuBtn txt="הפרוייקטים שלי" icon="city" href="/my_projects" />
        </section>
        <div className="h-10" />

        {children}
      </body>
    </html>
  )
}
