import TopMenuBtn from "@/components/TopMenuBtn"
import "@/styles/globals.scss"
import { Assistant } from "next/font/google"
import { ViewTransitions } from "next-view-transitions"

const font = Assistant({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <ViewTransitions>
      <html lang="he" dir="rtl">
        <body className={font.className}>
          <section className="nav top-0">
            <TopMenuBtn txt="הפרוייקטים שלי" icon="city" href="/my_projects" />
          </section>
          <div className="h-10" />

          {children}
        </body>
      </html>
    </ViewTransitions>
  )
}
