import TopMenuBtn from '@/components/TopMenuBtn'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function SetupLayout({ children, params: { prjId } }) {
  return (
    <div>
      <section className="nav">
        <TopMenuBtn txt="הפרוייקטים שלי" icon="city" href="/my_projects" />
        <TopMenuBtn txt="פרויקט הדסים" icon="building" href={`/project/${prjId}`} />
        <TopMenuBtn
          txt="הקמת פרויקט"
          icon="building-circle-check"
          href={`/project/${prjId}/parts`}
        />
        <TopMenuBtn txt="טבלת ביצועים" icon="qrcode" href={`/project/${prjId}/qr_table`} />
        <TopMenuBtn txt="בעיות ביצוע" icon="triangle-exclamation" href={`/project/${prjId}/test`} />
        <TopMenuBtn txt="בקשות חריגים" icon="hand-holding-dollar" href={`/project/${prjId}/test`} />
      </section>
      <div className="h-10" />
      <div>{children}</div>
    </div>
  )
}
