import TopMenuBtn from '@/components/TopMenuBtn'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function SetupLayout({ children, params: { prjId } }) {
  return (
    <div>
      <section className="nav top-10">
        <TopMenuBtn txt="פרויקט הדסים" icon="building" href={`/project/${prjId}`} />
        <TopMenuBtn
          txt="הקמת פרויקט"
          icon="building-circle-check"
          href={`/project/${prjId}/project_setup`}
        />
        <TopMenuBtn txt="שלבי ביצוע" icon="screwdriver-wrench" href={`/project/${prjId}/hatkana`} />
        <TopMenuBtn txt="הדפסת QR" icon="print" href={`/project/${prjId}/print`} />
      </section>

      <div>{children}</div>
    </div>
  )
}
