import SetupNav from '@/components/layout/SetupNav'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function SetupLayout({ children }) {
  return (
    <div>
      <SetupNav />
      <div>{children}</div>
    </div>
  )
}
