import { getUser } from '@/auth/authFuncs'
import '@/styles/globals.scss'
import UserProvider from '@/utils/userCtx'
import { Assistant } from 'next/font/google'
import GlobalPop from 'zvijude/pop'

const font = Assistant({ subsets: ['latin'] })

export const metadata = {
  title: 'Roi Crm',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const user = await getUser()
  return (
    <html lang="he" dir="rtl">
      <body className={font.className}>
        <UserProvider data={user}>
          <GlobalPop />
          {children}
        </UserProvider>
      </body>
    </html>
  )
}
