import TopMenuBtn from "@/components/TopMenuBtn"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

declare global {
  var prjId: number
}

export default function SetupLayout({ children, params }) {
  global.prjId = parseInt(params.id)
  console.log("global.prjId, from layout: ", global.prjId)

  return (
    <div>
      <section className="nav top-10">
        <TopMenuBtn txt="פרויקט הדסים" icon="building" href={`/project/${params.id}`} />
        <TopMenuBtn txt="כתב כמויות" icon="table-list" href={`/project/${params.id}/parts`} />
        {/* <Icon name="angles-right" /> */}
        <TopMenuBtn
          txt="שלבי ביצוע"
          icon="screwdriver-wrench"
          href={`/project/${params.id}/hatkana`}
        />
        {/* <Icon name="angles-right" /> */}
        <TopMenuBtn txt="הדפסת QR" icon="print" href={`/project/${params.id}/print`} />
      </section>
      <div className="h-10" />
      <div>{children}</div>
    </div>
  )
}
